### ISSUE TITLE
remove yarn from run scripts

### ISSUE THREAD

**Issue by wouterverweirder** [devinehowest/generator-devine-boilerplate#11]
Using "yarn run" inside package.json scripts forces the user to have yarn installed as a global dependency. We should either specify yarn as a dependency or use "npm run" inside our package.json.

I would prefer "npm run" instead of "yarn run" as I don't see a real benefit of running scripts through yarn. Yarn is nice to use to quickly install packages & locking versions, but it shouldn't be a requirement to run the scripts.

**Comment by geoffreydhuyvetters** [comment]
Ok, but I'm keeping the Yarn buildpack for faster installs + version lock on Heroku

**Comment by geoffreydhuyvetters** [comment]
https://github.com/devinehowest/generator-devine-project/commit/6d8c78a44889b0d613ae5fbf5970193fa2cc1db3

**Comment by geoffreydhuyvetters** [comment]
I should probably expand this to check if the user has Yarn
https://github.com/devinehowest/generator-devine-project/blob/v3/generators/app/index.js#L435

PR welcome
