### ISSUE TITLE
Spawn voor `git commit…` failt

### ISSUE THREAD

**Issue by thibmaek** [devinehowest/generator-devine-boilerplate#18]
Toch nog één klein foutje in de master geslopen 😄

My guess is omdat de `_spawn` helper split in binnenin de string van een commit message (https://github.com/devinehowest/generator-devine-project/blob/master/generators/app/index.js#L461)

![screenshot 2016-11-06 23 48 14](https://cloud.githubusercontent.com/assets/6213695/20042539/02d10c26-a47c-11e6-84f9-03cefe96b0dd.png)

**Comment by geoffreydhuyvetters** [comment]
lazy way.

https://github.com/devinehowest/generator-devine-project/commit/82e78efc85b67b486cb5556a813691f9e4eba571
