### ISSUE TITLE
loaders moeten -loader suffix hebben in webpack config

### ISSUE THREAD

**Issue by wouterverweirder** [devinehowest/generator-devine-boilerplate#19]
Gemerkt in laatste versie van webpack (webpack 2.1.0-beta.27):

```
BREAKING CHANGE: It's no longer allowed to omit the '-loader' prefix when using loaders.
                 You need to specify 'babel-loader' instead of 'babel'.
```

**Comment by geoffreydhuyvetters** [comment]
Aha, zal het nu al aanpassen maar ga nog eventjes wachten om te updaten. Of ben je vrij zeker dat alles nog altijd werkt (in hoeverre dat bestaat bij die webpack beta's)

**Comment by wouterverweirder** [comment]
Is verplicht geworden, webpack wil niet meer bundelen zonder die -loader in de laatste versie. Als je dus webpack@beta installed in een nieuw project (of je yarn.lockfile weggooit) dan werkt het niet meer.

**Comment by wouterverweirder** [comment]
Wel sympathiek dat ze gewacht hebben tot na de examenweek.

**Comment by geoffreydhuyvetters** [comment]
ok, heb een commit klaar

**Comment by geoffreydhuyvetters** [comment]
c-l-o-seddd https://github.com/devinehowest/generator-devine-boilerplate/commit/dba16e526e2ac8f6f399faab2828d31d79ae0f7a
