### ISSUE TITLE
Flow?

### ISSUE THREAD

**Issue by thibmaek** [devinehowest/generator-devine-boilerplate#20]
Toevoegen of buiten scope voor devine projecten?

https://github.com/duivvv/generator-module-boilerplate/commit/72ec224c397069cf7f33c33f99285c229ab547b0

**Comment by geoffreydhuyvetters** [comment]
Kan, als default (No).
Voor de durvers ;)

**Comment by thibmaek** [comment]
Alright zal pushen en PR'en binnen 5 mins ;)
