### ISSUE TITLE
react-devutils is installed even when react isn't selected

### ISSUE THREAD

**Issue by thibmaek** [devinehowest/generator-devine-boilerplate#25]
Probably because there is no check of the if clause is closed to soon.

**Comment by geoffreydhuyvetters** [comment]
Has nothing to do with react, is needed for the error reporting window. Exported in the  create-react-app monorepo.

I use for the custom webpackhotreload iFrame with the error messages 

https://github.com/devinehowest/generator-devine-boilerplate/blob/master/generators/app/templates/webpack.config.js#L34

related:
would love to implement this https://github.com/facebookincubator/create-react-app/pull/1101

**Comment by duivvv** [comment]
I use for the custom webpackhotreload iFrame with the error messages
