### ISSUE TITLE
Use zeit/serve in favor of 75lb/local-web-server

### ISSUE THREAD

**Issue by thibmaek** [devinehowest/generator-devine-boilerplate#32]
Had great results using this module and from checking both repo descriptions serve seems to do everything local-web-server does but only sits at ±150kb where local-web-server is 1MB+

serve defaults to gzipping assets (can be turned off), can be used to serve SPA and reads port from either a commandline flag or an env. Only thing missing here is SSL but it seems like we weren't using that for local-web-server either.

Let me know what the take on this is.

**Comment by geoffreydhuyvetters** [comment]
Cool. Can you create a PR. Gonna test it.
