### ISSUE TITLE
RFC: Prefer unfetch over isomorphic-fetch

### ISSUE THREAD

**Issue by thibmaek** [devinehowest/generator-devine-boilerplate#42]
Zou het waard kunnen zijn om te switchen eens ze het isomorphic gedeelte afhebben. https://github.com/developit/unfetch/pull/27
fs comparison ziet er alvast goed uit:

![image](https://cloud.githubusercontent.com/assets/6213695/23589451/a35104a4-01cd-11e7-8d42-5dd464c590bd.png)

**Comment by geoffreydhuyvetters** [comment]
cool, hou het in de gaten

**Comment by thibmaek** [comment]
Ga deze morgen lokaal eens proberen want zie dat die ref'd pr 3 dagen geleden ingemerged is. Will post output back here

**Comment by geoffreydhuyvetters** [comment]
@thibmaek wel spijtig dat je die niet hebt afgewerkt @thibmaek 😬

**Comment by thibmaek** [comment]
![image](https://user-images.githubusercontent.com/6213695/77047732-8dff1600-69c5-11ea-8b4a-54f7e5b0803a.png)
