### ISSUE TITLE
extract-text-webpack-plugin @beta not available

### ISSUE THREAD

**Issue by kevinmeyvaert** [devinehowest/generator-devine-boilerplate#43]
update to:
"extract-text-webpack-plugin": "^2.1.0"

**Comment by vjee** [comment]
Source has `"extract-text-webpack-plugin": "^2.0.0"` since quite a few commits already.
Sure you didn't forget to update your generator?

**Comment by geoffreydhuyvetters** [comment]
2.1.0 valt ook onder ^2.0.0 
semver hé :)

**Comment by thibmaek** [comment]
@kevinmeyvaert deze kan gesloten want was een shell issue right?

**Comment by kevinmeyvaert** [comment]
@thibmaek klopt. my bad.
