### ISSUE TITLE
'koa' breaking generator in environments running node < 7.6.0

### ISSUE THREAD

**Issue by vjee** [devinehowest/generator-devine-boilerplate#44]

**Comment by vjee** [comment]
problem:
`$ yarn` fails in node < 7.6.0 due to koa

The dependency that requires 'koa' is 'local-web-server'.

**steps taken to find out**

* dit grep search in node_modules folder
![grep](https://cloud.githubusercontent.com/assets/12999787/23766363/cec7bb8e-0504-11e7-804b-fb59929c90c2.png)
* second to last row points at 'local-web-server'
![grep - local-web-server](https://cloud.githubusercontent.com/assets/12999787/23766461/2d88cf50-0505-11e7-820b-a7bb749264f1.png)
* `$ yarn remove local-web-server`
* switch to node < 7.6.0 (used 7.5.0)
* `$ yarn`

yarn successfully installs all dependencies

**Comment by thibmaek** [comment]
Post error output van yarn dependency fetch please.

**Comment by thibmaek** [comment]
Of probeer es de cache te legen. Deze week geen issues gehad op volledige scaffold op LTS Argon

**Comment by vjee** [comment]
![yo devine-boilerplate](https://cloud.githubusercontent.com/assets/12999787/23770485/86431214-0513-11e7-93ab-b4d58a56dcd4.png)
![error messages](https://cloud.githubusercontent.com/assets/12999787/23770497/944d63dc-0513-11e7-9dfa-9374e4b7eba5.png)

* error on installing koa dependency
* stops installing
* starts `development` script
* can't find certain modules since yarn install didn't succeed

> Koa requires node v7.6.0 or higher for ES2015 and async function support.
> [koa on npm](https://www.npmjs.com/package/koa)

**Comment by vjee** [comment]
If I'm right, koa required node >=7.6.0 ugrading 2.0.1 to 2.1.0 which is only 2days ago, explaining why it only starts crashing now.

**Comment by thibmaek** [comment]
Heb hier kunnen replicaten. @duivvv misschien is het dan tijd om #33 es te reviseren? Zag er destijds goed uit maar geclosed omwille van node 6.9.0 min req. Dit breekt het sowieso ook en vereist een nog hogere versie + 6.9.0 is LTS anyway

**Comment by vjee** [comment]
@duivvv @thibmaek  What about using wsrv? [->wsrc on npm](https://www.npmjs.com/package/wsrv).
If it's only necessary to serve the production build this could be an okay package.
It uses hapi and doesn't have any crazy node requirement.

The `serve` script could then be something like `wsrv ./dist -p 3000 -o`.

**Comment by thibmaek** [comment]
I don't know. wsrv dep is dubbel de filesize van serve + laatste LTS lijkt me geen crazy node req om naar te migraten. In the long run verlies je toch functionaliteit met te blijven steken op een oudere LTS die phased out raakt op een bepaald punt door nieuwe LTS versies.

**Comment by geoffreydhuyvetters** [comment]
Voorlopig lijkt upgraden naar 7.6 of hoger de snelste optie, webpack dev server werkt nog na de upgrade.

**Comment by thibmaek** [comment]
Sounds fine.

**Comment by geoffreydhuyvetters** [comment]
Ben de laatste tijd wel fan van snelle node upgrades om eerlijk te zijn

**Comment by thibmaek** [comment]
Same here, zijn makkelijk te migraten + als elke even versie een LTS is met niet veel refactor werk zie ik geen reden om niet van 4 naar 6 te migraten bv.

**Comment by geoffreydhuyvetters** [comment]
"yarn why koa"

**Comment by vjee** [comment]
Ha didn't know that command. Would've been easier :p thanks!
